name: Update Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows you to manually trigger it from the Actions tab

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch YouTube Stats
      - name: Fetch YouTube Stats
        run: |
          echo "Fetching YouTube stats..."
          curl -s "https://www.googleapis.com/youtube/v3/channels?part=statistics&id=UCou82Q2T0gKgy2iD1RgNIOg&key=${{ secrets.YOUTUBE_API_KEY }}" > stats.json
          echo "Contents of stats.json:"
          cat stats.json # Debugging step to see the file contents

      # Step 3: Force Commit and Push
      - name: Commit and Push Stats
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.json
          git commit -m "Update stats" || echo "No changes detected in stats.json"
          git push || echo "Nothing to push"
